# Generated by Django 3.2 on 2021-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
